----------------------------------------------------------------------------------
-- Company: 
-- Engineer: 
-- 
-- Create Date: 05/10/2026 07:07:08 PM
-- Design Name: 
-- Module Name: vga_output_top - Behavioral
-- Project Name: 
-- Target Devices: 
-- Tool Versions: 
-- Description: 
-- 
-- Dependencies: 
-- 
-- Revision:
-- Revision 0.01 - File Created
-- Additional Comments:
-- 
----------------------------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
--USE IEEE.STD_LOGIC_ARITH.ALL; --used for conv_std_logic_vector
--USE IEEE.STD_LOGIC_UNSIGNED.ALL;

-- Uncomment the following library declaration if using
-- arithmetic functions with Signed or Unsigned values
use IEEE.NUMERIC_STD.ALL;

-- Uncomment the following library declaration if instantiating
-- any Xilinx leaf cells in this code.
--library UNISIM;
--use UNISIM.VComponents.all;


--library work;
---- this line also is must.This includes the particular package into your program.
--use work.commonPak.all;

entity vga_output_top is
--  Port ( );
    PORT (
        plaintext: IN std_logic_vector (439 downto 0);
        hash: IN std_logic_vector (255 downto 0);
        -- Clock input from board oscillator
        pxl_clk : IN STD_LOGIC; -- 100 MHz system clock
        
        -- VGA display outputs (4-bit color depth for 4096 colors)
        VGA_Red : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);   -- Red color channel
        VGA_Green : OUT STD_LOGIC_VECTOR (3 DOWNTO 0); -- Green color channel
        VGA_Blue : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);  -- Blue color channel
        VGA_HSync : OUT STD_LOGIC;  -- Horizontal sync signal
        VGA_VSync : OUT STD_LOGIC -- Vertical sync signal
    );
end vga_output_top;

architecture Behavioral of vga_output_top is
 -- Clock signals
    --SIGNAL pxl_clk : STD_LOGIC := '0'; -- 25 MHz pixel clock for VGA (generated by clock wizard)
    
    -- Color signals: Game engine outputs 1-bit colors, VGA needs 4-bit
    SIGNAL S_red, S_green, S_blue : STD_LOGIC;  -- Single-bit color from game engine
    SIGNAL S_red_vec, S_green_vec, S_blue_vec : STD_LOGIC_VECTOR (3 DOWNTO 0); -- 4-bit vectors for VGA
    
    -- VGA sync and pixel coordinates
    SIGNAL S_vsync : STD_LOGIC;  -- Vertical sync from VGA module
    SIGNAL S_pixel_row, S_pixel_col : STD_LOGIC_VECTOR (10 DOWNTO 0); -- Current pixel coordinates (0-799 cols, 0-599 rows)
    
    SIGNAL S_plaintext : STD_LOGIC_VECTOR (439 DOWNTO 0);
    SIGNAL S_hash : STD_LOGIC_VECTOR (255 DOWNTO 0);

    COMPONENT vga_font IS
        PORT (
            -- VGA synchronization and pixel coordinates
            v_sync : IN STD_LOGIC;  -- Vertical sync pulse (60Hz) - triggers game logic updates
            pixel_row : IN STD_LOGIC_VECTOR(10 DOWNTO 0);  -- Current pixel row (0-599)
            pixel_col : IN STD_LOGIC_VECTOR(10 DOWNTO 0);  -- Current pixel column (0-799)
            
            plaintext : IN STD_LOGIC_VECTOR(439 DOWNTO 0);
            hash : IN STD_LOGIC_VECTOR(255 DOWNTO 0);
            
            -- Color outputs (1-bit each, converted to 4-bit in top level)
            red : OUT STD_LOGIC;   -- Red color component
            green : OUT STD_LOGIC; -- Green color component
            blue : OUT STD_LOGIC  -- Blue color component
        );
    END COMPONENT;
    
    COMPONENT vga_sync IS
        PORT (
            pixel_clk : IN STD_LOGIC;
            red_in    : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
            green_in  : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
            blue_in   : IN STD_LOGIC_VECTOR (3 DOWNTO 0);
            red_out   : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
            green_out : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
            blue_out  : OUT STD_LOGIC_VECTOR (3 DOWNTO 0);
            hsync : OUT STD_LOGIC;
            vsync : OUT STD_LOGIC;
            pixel_row : OUT STD_LOGIC_VECTOR (10 DOWNTO 0);
            pixel_col : OUT STD_LOGIC_VECTOR (10 DOWNTO 0)
        );
    END COMPONENT;
    
--    COMPONENT clk_wiz_0 IS
--        PORT (
--            clk_in1  : IN STD_LOGIC;
--            clk_out1 : OUT STD_LOGIC
--        );
--    END COMPONENT;
begin
    -- ========================================================================
    -- Color Signal Conversion
    -- ========================================================================
    -- Game engine outputs single-bit color signals (on/off), but VGA interface
    -- requires 4-bit color vectors. We pad with zeros to create 4-bit values:
    -- '1' becomes "1000" (bright), '0' becomes "0000" (black).
    S_red_vec <= S_red & "000";
    S_green_vec <= S_green & "000";
    S_blue_vec <= S_blue & "000";
    
    --HELLO WORLD codes for debugging
    --S_plaintext <= x"48454C4C4F20574F524C4400000000000000000000000000000000048454C4C4F20574F524C44000000000000000000000000000000000";
    --S_plaintext <= x"48454C4C4F20574F524C4448454C4C4F20574F524C4448454C4C4F20574F524C4448454C4C4F20574F524C4448454C4C4F20574F524C44";
    font_driver : vga_font
    PORT MAP(
        v_sync => S_vsync,
        pixel_row => S_pixel_row,
        pixel_col => S_pixel_col,
        
        plaintext => S_plaintext,
        hash => S_hash,
        
        red => S_red,
        green => S_green,
        blue => S_blue
    );

    vga_driver : vga_sync
    PORT MAP(
        pixel_clk => pxl_clk,        -- 25 MHz pixel clock from clock wizard
        red_in => S_red_vec,         -- 4-bit red color input
        green_in => S_green_vec,     -- 4-bit green color input
        blue_in => S_blue_vec,       -- 4-bit blue color input
        red_out => VGA_Red,          -- VGA red output (with blanking)
        green_out => VGA_Green,      -- VGA green output (with blanking)
        blue_out => VGA_Blue,        -- VGA blue output (with blanking)
        pixel_row => S_pixel_row,    -- Current pixel row (output to game)
        pixel_col => S_pixel_col,    -- Current pixel column (output to game)
        hsync => VGA_HSync,          -- Horizontal sync signal
        vsync => S_vsync             -- Vertical sync signal (also used by game)
    );
    VGA_VSync <= S_vsync; -- Route vsync to output port

    -- ========================================================================
    -- Clock Wizard Component Instantiation
    -- ========================================================================
--    clk_wiz_0_inst : clk_wiz_0
--    PORT MAP (
--        clk_in1 => CLK100MHZ,   -- 100 MHz system clock input
--        clk_out1 => pxl_clk  -- ~25 MHz pixel clock output
--    );
    
    
end Behavioral;